name: transactions-service-prod

services:
  api:
    image: transactions-service:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      gunicorn app.config.app:app
      --workers 4
      --worker-class uvicorn.workers.UvicornWorker
      --bind 0.0.0.0:7999
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod

  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started

volumes:
  postgres-data-prod:
    name: transactions-postgres-prod
