name: transactions-service-prod

services:
  api:
    image: transactions-service:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file:
      - .env.prod
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:7999/')" ]
      interval: 5s
      timeout: 3s
      retries: 10

  db:
    image: postgres:17
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod

  nginx:
    build: nginx
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_healthy

volumes:
  postgres-data-prod:
    name: transactions-postgres-prod
