from fastapi import HTTPException


class UserAlreadyExistsException(HTTPException): ...


class UserNotExistsException(HTTPException): ...


class UserAlreadyBlockedException(HTTPException): ...


class UserAlreadyActiveException(HTTPException): ...


class NegativeBalanceException(HTTPException): ...
